// Generated by 02_devtools/import-student-panda-growth.mjs from archived user SVGs.
// Do not redraw or hand-edit paths here; re-import the approved SVGs.
import PandaWardrobeArtwork from "./PandaWardrobeArtwork.jsx";

function Stage0({ prefix }) {
  return (
    <>
      <defs />
      <g id={prefix + "-s0-0"}>
        <g className={"panda-mascot__egg panda-mascot__action"} data-motion-part={"egg"}>
          <g id={prefix + "-s0-1"} data-group={"closed-egg"} data-part={"closed-egg"}>
            <g id={prefix + "-s0-2"} data-part={"egg-base"}>
              <path id={prefix + "-s0-3"} d={"M307,811c0,199,115,306,320,306s318-107,318-306c0-216-174-469-318-469-144,0-320,253-320,469Z"} fill={"#f5f0e4"} />
            </g>
            <g id={prefix + "-s0-4"} data-part={"egg-light"}>
              <path id={prefix + "-s0-5"} d={"M670,349c96,70,165,211,173,360,6,99-9,210-80,289-71,79-192,114-297,85-98-27-159-121-159-272,0-216,176-469,320-469,15,0,29,2,43,7Z"} fill={"#fffefa"} />
            </g>
            <g id={prefix + "-s0-6"} data-part={"egg-spot-top"}>
              <ellipse id={prefix + "-s0-7"} cx={"462"} cy={"562"} rx={"67"} ry={"47"} transform={"translate(-263.4 618.1) rotate(-55)"} fill={"#f6edde"} />
            </g>
            <g id={prefix + "-s0-8"} data-part={"egg-spot-left"}>
              <ellipse id={prefix + "-s0-9"} cx={"748"} cy={"856"} rx={"49"} ry={"38"} transform={"translate(-367.3232 1075.7901) rotate(-60)"} fill={"#f6edde"} />
            </g>
            <g id={prefix + "-s0-10"} data-part={"egg-spot-right"}>
              <ellipse id={prefix + "-s0-11"} cx={"441"} cy={"880"} rx={"85"} ry={"126"} transform={"translate(-351.4 296.1) rotate(-27)"} fill={"#f6edde"} />
            </g>
          </g>
        </g>
      </g>
    </>
  );
}

function Stage1({ prefix }) {
  return (
    <>
      <defs>
        <clipPath id={prefix + "-s1-0"}>
          <path d={"M580 627C594 627 609 629 624 629C639 629 654 627 666 627C676 627 681 632 681 642C681 673 656 704 624 704C592 704 563 673 563 642C563 632 568 627 580 627Z"} transform={"translate(592 775) scale(0.559322033898305 0.5844155844155844) translate(-563 -627)"} />
        </clipPath>
      </defs>
      <g id={prefix + "-s1-1"}>
        <g>
          <g id={prefix + "-s1-2"} data-group={"body"} data-part={"body"}>
            <g id={prefix + "-s1-3"} data-part={"torso"}>
              <path id={prefix + "-s1-4"} d={"M625,815.9c84,0,148.5,91.5,145.5,177-2.2,46.5-56.2,69-145.5,69s-144.8-21.8-146.2-69c-3-83.2,61.5-177,146.2-177Z"} fill={"#1c1d19"} />
            </g>
            <g id={prefix + "-s1-5"} data-part={"belly"}>
              <path id={prefix + "-s1-6"} d={"M625,841.4c66.8,0,133.5,92.2,141.8,140.2,11.2,64.5-51,93-141.8,93s-152.2-22.5-147-84c3-57,80.2-149.2,147-149.2h0Z"} fill={"#fffefa"} />
            </g>
            <g id={prefix + "-s1-7"} data-group={"scarf"} data-part={"scarf"}>
              <g id={prefix + "-s1-8"} data-part={"scarf-cloth"}>
                <path id={prefix + "-s1-9"} d={"M490,816.6c33-16.5,87-23.2,135-23.2s104.2,6.8,135,23.2c9.8,15.8,9,36,.8,51-14.2,25.5-41.2,46.5-70.5,68.2-22.5,17.2-46.5,32.2-65.2,44.2-21-12-45-27.8-68.2-43.5-29.2-21.8-52.5-42.8-66-65.2-10.5-17.2-13.5-39-.8-54.8Z"} fill={"#90050e"} />
              </g>
              <g id={prefix + "-s1-10"} data-part={"scarf-fold"}>
                <path id={prefix + "-s1-11"} d={"M484.8,851.1c93,27.5,186.2,27.5,279.8,0-3.5,13.5-50.2,31-140.2,52.5-76.5-20.5-123-38-139.5-52.5Z"} fill={"#75020b"} />
              </g>
            </g>
          </g>
          <g id={prefix + "-s1-12"} data-group={"shell"} data-part={"shell"}>
            <g id={prefix + "-s1-13"} data-part={"shell-base"}>
              <path id={prefix + "-s1-14"} d={"M393.8,885l59.4,53.1,62.5-46.9,90.6,68.8,75-62.5,84.4,43.8,90.6-62.5c15.6,146.9-84.4,250-231.2,253.1-146.9-3.1-246.9-106.2-231.2-246.9h0Z"} fill={"#fff9e9"} />
            </g>
            <g id={prefix + "-s1-15"} data-part={"shell-highlight"}>
              <path id={prefix + "-s1-16"} d={"M445.8,1005.3c23.1,48.9,60.1,75.7,110.4,89.1"} fill={"none"} stroke={"#fffefa"} strokeLinecap={"round"} strokeWidth={"15.6px"} />
            </g>
          </g>
          <g id={prefix + "-s1-17"} data-group={"arms"} data-part={"arms"}>
            <g className={"panda-mascot__arm-idle panda-mascot__arm-idle--right"} data-motion-part={"arm"}>
              <g className={"panda-mascot__arm-wave panda-mascot__arm-wave--right"} data-motion-part={"arm-wave"}>
                <g id={prefix + "-s1-18"} data-part={"arm-right"}>
                  <path id={prefix + "-s1-19"} d={"M720.5,806c-51.6,19.6-15.5,46.9-7.7,84.2s-1.2,57.6,42.6,64c17.4,2.6,44.5-4.2,52.2-30.8,14.8-50.9-44.8-112-87.2-117.4Z"} fill={"#1c1d19"} />
                </g>
              </g>
            </g>
          </g>
          <g id={prefix + "-s1-20"} data-group={"arms"} data-part={"arms"}>
            <g className={"panda-mascot__arm-idle panda-mascot__arm-idle--left"} data-motion-part={"arm"}>
              <g className={"panda-mascot__arm-wave panda-mascot__arm-wave--left"} data-motion-part={"arm-wave"}>
                <g id={prefix + "-s1-21"} data-part={"arm-left"}>
                  <path id={prefix + "-s1-22"} d={"M442.3,923.4c7.7,26.6,34.8,33.4,52.2,30.8,43.9-6.4,39.7-50.2,42.6-64,7.9-37.3,43.9-64.6-7.7-84.2-42.4,5.4-102,66.5-87.2,117.4Z"} fill={"#1c1d19"} />
                </g>
              </g>
            </g>
          </g>
          <g className={"panda-mascot__head-breath"}>
            <g className={"panda-mascot__head-action panda-mascot__action"} data-motion-part={"head"}>
              <g id={prefix + "-s1-23"} data-group={"head"} data-part={"head"}>
                <g id={prefix + "-s1-24"} data-group={"ears"} data-part={"ears"}>
                  <g className={"panda-mascot__ear-action panda-mascot__ear-action--right"} data-motion-part={"ear"}>
                    <g id={prefix + "-s1-25"} data-part={"ear-right"}>
                      <path id={prefix + "-s1-26"} d={"M723.8,513.6c0-40.5,32.8-73.4,73.4-73.4s73.4,32.8,73.4,73.4-32.8,73.4-73.4,73.4-73.4-32.8-73.4-73.4h0Z"} fill={"#1c1d19"} />
                    </g>
                  </g>
                </g>
                <g id={prefix + "-s1-27"} data-group={"ears"} data-part={"ears"}>
                  <g className={"panda-mascot__ear-action panda-mascot__ear-action--left"} data-motion-part={"ear"}>
                    <g id={prefix + "-s1-28"} data-part={"ear-left"}>
                      <path id={prefix + "-s1-29"} d={"M526.2,513.6c0,40.6-32.8,73.4-73.4,73.4-40.6,0-73.4-32.8-73.4-73.4,0-40.6,32.8-73.4,73.4-73.4,40.6,0,73.4,32.9,73.4,73.4h0Z"} fill={"#1c1d19"} />
                    </g>
                  </g>
                </g>
                <g id={prefix + "-s1-30"} data-part={"face-base"}>
                  <path id={prefix + "-s1-31"} d={"M625,457.9c-310.2,1.1-390.8,435.2,0,412.7,71.3,0,143.4-10.7,185.7-36.1,48.4-29,75.7-63.4,75.7-143.4-3-141.8-113.9-233.1-261.4-233.2Z"} fill={"#fffefa"} />
                </g>
                <g id={prefix + "-s1-32"} data-group={"facial-features"} data-part={"facial-features"}>
                  <g id={prefix + "-s1-33"} data-group={"eye-left"} data-part={"eye-left"}>
                    <g id={prefix + "-s1-34"} data-part={"eye-patch-left"}>
                      <path id={prefix + "-s1-35"} d={"M567.2,727.3c-17.6,37.8-57.9,56.3-89.8,41.5-32-15-43.7-57.6-26-95.5,17.6-37.8,57.9-56.3,89.8-41.5,32,15,43.7,57.6,26,95.5Z"} fill={"#1c1d19"} />
                    </g>
                    <g className={"panda-mascot__eyes-open panda-mascot__action"} data-motion-part={"eye"}>
                      <g className={"panda-mascot__pupil-look"} data-motion-part={"pupil"}>
                        <g id={prefix + "-s1-36"} data-part={"eye-white-left"}>
                          <ellipse id={prefix + "-s1-37"} cx={"535.8"} cy={"691.5"} rx={"20"} ry={"28.3"} fill={"#fff"} />
                        </g>
                      </g>
                    </g>
                  </g>
                  <g id={prefix + "-s1-38"} data-group={"eye-right"} data-part={"eye-right"}>
                    <g id={prefix + "-s1-39"} data-part={"eye-patch-right"}>
                      <path id={prefix + "-s1-40"} d={"M797.8,673.2c17.6,37.8,5.9,80.5-26,95.5-32,15-72.2-3.6-89.8-41.5s-5.9-80.5,26-95.5c32-15,72.2,3.6,89.8,41.5Z"} fill={"#1c1d19"} />
                    </g>
                    <g className={"panda-mascot__eyes-open panda-mascot__action"} data-motion-part={"eye"}>
                      <g className={"panda-mascot__pupil-look"} data-motion-part={"pupil"}>
                        <g id={prefix + "-s1-41"} data-part={"eye-white-right"}>
                          <ellipse id={prefix + "-s1-42"} cx={"714.2"} cy={"691.5"} rx={"20"} ry={"28.3"} fill={"#fff"} />
                        </g>
                      </g>
                    </g>
                  </g>
                  <g className={"panda-mascot__cheek panda-mascot__action"}>
                    <g id={prefix + "-s1-43"} data-part={"cheek-left"}>
                      <path id={prefix + "-s1-44"} d={"M501.8,802.7c0,13.6-15.8,24.6-35.2,24.6s-35.2-11-35.2-24.6,15.8-24.6,35.2-24.6,35.2,11,35.2,24.6Z"} fill={"#fd5d72"} />
                    </g>
                  </g>
                  <g className={"panda-mascot__cheek panda-mascot__action"}>
                    <g id={prefix + "-s1-45"} data-part={"cheek-right"}>
                      <path id={prefix + "-s1-46"} d={"M816,802.7c0,13.6-15.8,24.6-35.2,24.6s-35.2-11-35.2-24.6,15.8-24.6,35.2-24.6,35.2,11,35.2,24.6Z"} fill={"#fd5d72"} />
                    </g>
                  </g>
                  <g id={prefix + "-s1-47"} data-part={"nose"}>
                    <path id={prefix + "-s1-48"} d={"M655.8,731.1c0,10.2-14.2,18.5-31.7,18.5s-31.7-8.3-31.7-18.5,14.2-18.5,31.7-18.5,31.7,8.3,31.7,18.5Z"} fill={"#1c1d19"} />
                  </g>
                  <g className={"panda-mascot__mouth panda-mascot__action"} data-motion-part={"mouth"}>
                    <g className={"panda-mascot__pacifier"}>
                      <g id={prefix + "-s1-49"} data-group={"pacifier"} data-part={"pacifier"}>
                        <g id={prefix + "-s1-50"} data-part={"pacifier-shield"}>
                          <path id={prefix + "-s1-51"} d={"M625,762.8c-15,0-35.2-13.2-51.9-1.8-15,10.6-13.2,31.7-3.5,49.3,11.4,20.2,33.4,26.4,55.4,26.4s44-6.2,55.4-26.4c9.7-17.6,11.4-38.7-3.5-49.3-16.7-11.4-37,1.8-51.9,1.8Z"} fill={"#b30b2d"} />
                        </g>
                        <g id={prefix + "-s1-52"} data-part={"pacifier-hole-left"}>
                          <ellipse id={prefix + "-s1-53"} cx={"582.8"} cy={"780.4"} rx={"7"} ry={"8.8"} fill={"#fffefa"} />
                        </g>
                        <g id={prefix + "-s1-54"} data-part={"pacifier-hole-right"}>
                          <ellipse id={prefix + "-s1-55"} cx={"667.2"} cy={"780.4"} rx={"7"} ry={"8.8"} fill={"#fffefa"} />
                        </g>
                        <g id={prefix + "-s1-56"} data-part={"pacifier-ring"}>
                          <path id={prefix + "-s1-57"} d={"M625,779.5c21.4,0,38.7,17.3,38.7,38.7s-17.3,38.7-38.7,38.7-38.7-17.3-38.7-38.7,17.3-38.7,38.7-38.7ZM625,795.4c-12.6,0-22.9,10.2-22.9,22.9s10.2,22.9,22.9,22.9,22.9-10.2,22.9-22.9-10.2-22.9-22.9-22.9Z"} fill={"#ff8170"} fillRule={"evenodd"} />
                        </g>
                        <g id={prefix + "-s1-58"} data-part={"pacifier-hub"}>
                          <ellipse id={prefix + "-s1-59"} cx={"625"} cy={"791"} rx={"20.2"} ry={"21.1"} fill={"#ff9682"} />
                        </g>
                      </g>
                    </g>
                    <g className={"panda-mascot__baby-mouth"} data-part={"mouth"}>
                      <g className={"panda-mascot__mouth-open panda-mascot__action"}>
                        <g>
                          <path d={"M580 627C594 627 609 629 624 629C639 629 654 627 666 627C676 627 681 632 681 642C681 673 656 704 624 704C592 704 563 673 563 642C563 632 568 627 580 627Z"} fill={"#1c1d19"} transform={"translate(592 775) scale(0.559322033898305 0.5844155844155844) translate(-563 -627)"} />
                          <g clipPath={"url(#" + prefix + "-s1-0)"}>
                            <path d={"M668 686C668 704.78 648.3 720 624 720C599.7 720 580 704.78 580 686C580 667.22 599.7 652 624 652C648.3 652 668 667.22 668 686Z"} fill={"#fe7355"} transform={"translate(592 775) scale(0.559322033898305 0.5844155844155844) translate(-563 -627)"} />
                          </g>
                        </g>
                      </g>
                      <g className={"panda-mascot__mouth-closed panda-mascot__action"} data-part={"mouth-chew-closed"}>
                        <path d={"M579 639C593 644 608 647 624 647C640 647 655 644 668 639C672 637 675 641 672 645C660 657 641 662 624 662C607 662 587 657 575 645C572 641 575 637 579 639Z"} fill={"#1c1d19"} transform={"translate(592 775) scale(0.559322033898305 0.5844155844155844) translate(-563 -627)"} />
                      </g>
                    </g>
                  </g>
                </g>
              </g>
            </g>
          </g>
        </g>
      </g>
    </>
  );
}

function Stage2({ prefix }) {
  return (
    <>
      <defs>
        <clipPath id={prefix + "-s2-0"}>
          <path d={"M580 627C594 627 609 629 624 629C639 629 654 627 666 627C676 627 681 632 681 642C681 673 656 704 624 704C592 704 563 673 563 642C563 632 568 627 580 627Z"} fill={"none"} transform={"translate(588 772.3612) scale(0.5966101694915255 0.6290753246753247) translate(-563 -627)"} />
        </clipPath>
        <linearGradient id={prefix + "-s2-1"} x1={"553.8"} y1={"690.4"} x2={"925.8"} y2={"183"} gradientTransform={"translate(146.1 249.7) rotate(71.5) scale(1 -1)"} gradientUnits={"userSpaceOnUse"}>
          <stop offset={"0"} stopColor={"#1c1d19"} />
          <stop offset={"1"} stopColor={"#191916"} />
        </linearGradient>
        <linearGradient id={prefix + "-s2-2"} x1={"553.8"} y1={"690.4"} x2={"925.8"} y2={"183"} gradientTransform={"translate(1103.8556 249.6686) rotate(108.5316)"} href={"#" + prefix + "-s2-1"} />
      </defs>
      <g id={prefix + "-s2-3"}>
        <g>
          <g id={prefix + "-s2-4"} data-group={"seated-body"} data-part={"seated-body"}>
            <g id={prefix + "-s2-5"} data-part={"torso"}>
              <path id={prefix + "-s2-6"} d={"M625,819.4c79,0,147,64,158,151,8,68-10,124-52,139-33,13-67,14-106,14s-73-1-106-14c-42-15-60-71-52-139,11-87,79-151,158-151Z"} fill={"#1c1d19"} />
            </g>
            <g id={prefix + "-s2-7"} data-part={"belly"}>
              <path id={prefix + "-s2-8"} d={"M625,859.8c68,0,122,65,136,139,13,77-45,118-136,118s-149-41-136-118c14-74,68-139,136-139Z"} fill={"#fffefa"} />
            </g>
          </g>
          <g id={prefix + "-s2-9"} data-group={"scarf-size"} data-part={"scarf-size"}>
            <g id={prefix + "-s2-10"} data-group={"scarf"} data-part={"scarf"}>
              <g id={prefix + "-s2-11"} data-part={"scarf-cloth"}>
                <path id={prefix + "-s2-12"} d={"M497.2,833.6c31.2-15.6,82.4-22,127.8-22s98.7,6.4,127.8,22c9.2,14.9,8.5,34.1.7,48.3-13.5,24.1-39,44-66.7,64.6-21.3,16.3-44,30.5-61.8,41.9-19.9-11.4-42.6-26.3-64.6-41.2-27.7-20.6-49.7-40.5-62.5-61.8-9.9-16.3-12.8-36.9-.7-51.8Z"} fill={"#90050e"} />
              </g>
              <g id={prefix + "-s2-13"} data-part={"scarf-fold"}>
                <path id={prefix + "-s2-14"} d={"M492.2,866.2c88,26,176.3,26,264.8,0-3.3,12.8-47.6,29.3-132.8,49.7-72.4-19.4-116.4-36-132.1-49.7Z"} fill={"#75020b"} />
              </g>
            </g>
          </g>
          <g className={"panda-mascot__head-breath"}>
            <g className={"panda-mascot__head-action panda-mascot__action"} data-motion-part={"head"}>
              <g id={prefix + "-s2-15"} data-group={"head"} data-part={"head"}>
                <g id={prefix + "-s2-16"} data-group={"ears"} data-part={"ears"}>
                  <g className={"panda-mascot__ear-action panda-mascot__ear-action--left"} data-motion-part={"ear"}>
                    <g id={prefix + "-s2-17"} data-part={"ear-left"}>
                      <path id={prefix + "-s2-18"} d={"M363.2,534.8c0-41,33.6-74.2,75-74.2s75,33.2,75,74.2-33.6,74.2-75,74.2-75-33.2-75-74.2Z"} fill={"#1c1d19"} />
                    </g>
                  </g>
                  <g className={"panda-mascot__ear-action panda-mascot__ear-action--right"} data-motion-part={"ear"}>
                    <g id={prefix + "-s2-19"} data-part={"ear-right"}>
                      <path id={prefix + "-s2-20"} d={"M741.1,533.2c0-41.4,33.6-75,75-75s75,33.6,75,75-33.6,75-75,75-75-33.6-75-75Z"} fill={"#1c1d19"} />
                    </g>
                  </g>
                </g>
                <g id={prefix + "-s2-21"} data-part={"hair-tuft"}>
                  <path id={prefix + "-s2-22"} d={"M587.3,518.3c-3.4-33.8,7.9-66.5,30.4-84.5,19.2-15.8,42.8-10.1,53,7.9,12.4,22.5-4.5,49.6-21.4,69.9-16.9,14.7-45.1,16.9-62,6.8Z"} fill={"#fffefa"} />
                </g>
                <g id={prefix + "-s2-23"} data-part={"face-base"}>
                  <path id={prefix + "-s2-24"} d={"M625,472.3c-78.3,0-123.8,21.5-158.2,47.3-61.1,45.8-98.9,115.2-98.9,180.6s28.4,111.8,75.7,140.2c41.3,24.8,111.8,35.3,181.5,35.3s140.2-10.5,181.5-35.3c47.3-28.4,74-61.9,74-140.2s-36.1-134.8-97.2-180.6-80-47.3-158.2-47.3Z"} fill={"#fffefa"} />
                </g>
                <g id={prefix + "-s2-25"} data-group={"facial-features"} data-part={"facial-features"}>
                  <g id={prefix + "-s2-26"} data-group={"eye-left"} data-part={"eye-left"}>
                    <g id={prefix + "-s2-27"} data-part={"eye-patch-left"}>
                      <path id={prefix + "-s2-28"} d={"M566.5,728c-16.6,35.6-54.5,53.1-84.6,39-30.1-14-41.1-54.3-24.5-89.9,16.6-35.6,54.5-53.1,84.6-39,30.1,14,41.1,54.3,24.5,89.9Z"} fill={"#1c1d19"} />
                    </g>
                    <g className={"panda-mascot__eyes-open panda-mascot__action"} data-motion-part={"eye"}>
                      <g className={"panda-mascot__pupil-look"} data-motion-part={"pupil"}>
                        <g id={prefix + "-s2-29"} data-part={"eye-white-left"}>
                          <ellipse id={prefix + "-s2-30"} cx={"538.5"} cy={"694"} rx={"18"} ry={"26.5"} fill={"#fff"} />
                        </g>
                      </g>
                    </g>
                  </g>
                  <g id={prefix + "-s2-31"} data-group={"eye-right"} data-part={"eye-right"}>
                    <g id={prefix + "-s2-32"} data-part={"eye-patch-right"}>
                      <path id={prefix + "-s2-33"} d={"M791.8,677.2c16.6,35.6,5.6,75.8-24.5,89.9-30.1,14-68-3.4-84.6-39-16.6-35.6-5.6-75.8,24.5-89.9,30.1-14,68,3.4,84.6,39Z"} fill={"#1c1d19"} />
                    </g>
                    <g className={"panda-mascot__eyes-open panda-mascot__action"} data-motion-part={"eye"}>
                      <g className={"panda-mascot__pupil-look"} data-motion-part={"pupil"}>
                        <g id={prefix + "-s2-34"} data-part={"eye-white-right"}>
                          <ellipse id={prefix + "-s2-35"} cx={"711.5"} cy={"694"} rx={"18"} ry={"26.5"} fill={"#fff"} />
                        </g>
                      </g>
                    </g>
                  </g>
                  <g className={"panda-mascot__cheek panda-mascot__action"}>
                    <g id={prefix + "-s2-36"} data-part={"cheek-left"}>
                      <path id={prefix + "-s2-37"} d={"M504.6,798.9c0,13.3-15.4,24.1-34.4,24.1s-34.4-10.8-34.4-24.1,15.4-24.1,34.4-24.1,34.4,10.8,34.4,24.1Z"} fill={"#fd5d72"} />
                    </g>
                  </g>
                  <g className={"panda-mascot__cheek panda-mascot__action"}>
                    <g id={prefix + "-s2-38"} data-part={"cheek-right"}>
                      <path id={prefix + "-s2-39"} d={"M811.6,798.9c0,13.3-15.4,24.1-34.4,24.1s-34.4-10.8-34.4-24.1,15.4-24.1,34.4-24.1,34.4,10.8,34.4,24.1Z"} fill={"#fd5d72"} />
                    </g>
                  </g>
                  <g id={prefix + "-s2-40"} data-part={"nose"}>
                    <path id={prefix + "-s2-41"} d={"M655.1,739.6c0,10-13.9,18.1-31,18.1s-31-8.1-31-18.1,13.9-18.1,31-18.1,31,8.1,31,18.1Z"} fill={"#1c1d19"} />
                  </g>
                  <g className={"panda-mascot__mouth panda-mascot__action"} data-motion-part={"mouth"}>
                    <g className={"panda-mascot__mouth-open panda-mascot__action"}>
                      <g id={prefix + "-s2-42"} data-group={"mouth"} data-part={"mouth"}>
                        <g id={prefix + "-s2-43"} data-part={"mouth-cavity"}>
                          <path id={prefix + "-s2-44"} d={"M580 627C594 627 609 629 624 629C639 629 654 627 666 627C676 627 681 632 681 642C681 673 656 704 624 704C592 704 563 673 563 642C563 632 568 627 580 627Z"} fill={"#1c1d19"} transform={"translate(588 772.3612) scale(0.5966101694915255 0.6290753246753247) translate(-563 -627)"} />
                        </g>
                        <g clipPath={"url(#" + prefix + "-s2-0)"}>
                          <g id={prefix + "-s2-45"} data-group={"tongue-mask"} data-part={"tongue-mask"}>
                            <g id={prefix + "-s2-46"} data-part={"tongue"}>
                              <path id={prefix + "-s2-47"} d={"M668 686C668 704.78 648.3 720 624 720C599.7 720 580 704.78 580 686C580 667.22 599.7 652 624 652C648.3 652 668 667.22 668 686Z"} fill={"#fe7355"} transform={"translate(588 772.3612) scale(0.5966101694915255 0.6290753246753247) translate(-563 -627)"} />
                            </g>
                          </g>
                        </g>
                      </g>
                    </g>
                    <g className={"panda-mascot__mouth-closed panda-mascot__action"} data-part={"mouth-chew-closed"}>
                      <path d={"M579 639C593 644 608 647 624 647C640 647 655 644 668 639C672 637 675 641 672 645C660 657 641 662 624 662C607 662 587 657 575 645C572 641 575 637 579 639Z"} fill={"#1c1d19"} transform={"translate(588 772.3612) scale(0.5966101694915255 0.6290753246753247) translate(-563 -627)"} />
                    </g>
                  </g>
                </g>
              </g>
            </g>
          </g>
          <g id={prefix + "-s2-48"} data-group={"bottle"} data-part={"bottle"}>
            <g id={prefix + "-s2-49"} data-part={"bottle-body"}>
              <path id={prefix + "-s2-50"} d={"M587,905.3c-8,12-18,26-18,47v69c0,28,17,36,56,36s56-8,56-36v-69c0-21-10-35-18-47h-76Z"} fill={"#b7ded4"} />
            </g>
            <g id={prefix + "-s2-51"} data-part={"bottle-inner"}>
              <path id={prefix + "-s2-52"} d={"M594,911.3c-11,18-16,26-16,44v62c0,21,13,30,47,30s47-9,47-30v-62c0-18-5-26-16-44h-62Z"} fill={"#fff"} />
            </g>
            <g id={prefix + "-s2-53"} data-part={"bottle-milk"}>
              <path id={prefix + "-s2-54"} d={"M578,954.3h94v63c0,22-15,30-47,30s-47-8-47-30v-63Z"} fill={"#faf3e3"} />
            </g>
            <g id={prefix + "-s2-55"} data-part={"bottle-nipple"}>
              <path id={prefix + "-s2-56"} d={"M588,891.3c0-20,11-30,24-38v-13c0-17,26-17,26,0v13c13,8,24,18,24,38h-74Z"} fill={"#ffb08b"} />
            </g>
            <g id={prefix + "-s2-57"} data-part={"bottle-nipple-shine"}>
              <path id={prefix + "-s2-58"} d={"M622.1,833.6c-3.7,1.3-4.3,5.3-4.2,11"} fill={"none"} stroke={"#ffd2b7"} strokeLinecap={"round"} strokeWidth={"6px"} />
            </g>
            <g id={prefix + "-s2-59"} data-part={"bottle-collar"}>
              <rect id={prefix + "-s2-60"} x={"577"} y={"885.3"} width={"96"} height={"29"} rx={"13"} ry={"13"} fill={"#90ccbb"} />
            </g>
            <g id={prefix + "-s2-61"} data-part={"bottle-shine"}>
              <path id={prefix + "-s2-62"} d={"M597,946.3h0c3.3,0,6,2.7,6,6v56c0,3.3-2.7,6-6,6h0c-3.3,0-6-2.7-6-6v-56c0-3.3,2.7-6,6-6Z"} fill={"#fff"} />
            </g>
          </g>
          <g id={prefix + "-s2-63"} data-part={"arm-right"}>
            <path id={prefix + "-s2-64"} d={"M769.8,870.7c-13-13-31.2-10.3-57.7,14.6-18.7,16.3-31,19-49.1,26-33.3,12.8-40,84.6,22.6,82,30.1-1.2,70.7-21.8,87.6-52.2s13.3-53.8-3.4-70.4Z"} fill={"url(#" + prefix + "-s2-1)"} />
          </g>
          <g id={prefix + "-s2-65"} data-part={"arm-left"}>
            <path id={prefix + "-s2-66"} d={"M476.8,941.1c17,30.4,57.5,51,87.6,52.2,62.6,2.6,55.9-69.2,22.6-82-18.1-7-30.4-9.7-49.1-26-26.5-24.9-44.7-27.6-57.7-14.6-16.7,16.6-15.8,48.2-3.4,70.4Z"} fill={"url(#" + prefix + "-s2-2)"} />
          </g>
          <g id={prefix + "-s2-67"} data-part={"leg-right"}>
            <path id={prefix + "-s2-68"} d={"M745.5,1006.2c-31.9-.5-60.7,29-69,63s14.8,64.5,53,63,69.9-24,83.9-58,5-65-24-73c-17-5-28.9-2-43.9,5Z"} fill={"#1c1d19"} />
          </g>
          <g id={prefix + "-s2-69"} data-part={"leg-left"}>
            <path id={prefix + "-s2-70"} d={"M460.6,1001.2c-29,8-38,39-24,73,14,34,45.7,56.5,83.9,58,38.2,1.5,61.3-29,53-63-8.3-34-37.1-63.5-69-63-15-7-26.9-10-43.9-5Z"} fill={"#1c1d19"} />
          </g>
        </g>
      </g>
    </>
  );
}

function Stage3({ prefix }) {
  return (
    <>
      <defs>
        <linearGradient id={prefix + "-s3-0"} x1={"203"} y1={"727.5"} x2={"754.5"} y2={"-24.9"} gradientTransform={"translate(0 1254) scale(1 -1)"} gradientUnits={"userSpaceOnUse"}>
          <stop offset={"0"} stopColor={"#1c1d19"} />
          <stop offset={"1"} stopColor={"#191916"} />
        </linearGradient>
        <linearGradient id={prefix + "-s3-1"} x1={"203.1"} y1={"727.5"} x2={"754.6"} y2={"-24.9"} gradientTransform={"translate(1250 1254) rotate(-180)"} href={"#" + prefix + "-s3-0"} />
        <clipPath id={prefix + "-s3-2"}>
          <path d={"M580 627C594 627 609 629 624 629C639 629 654 627 666 627C676 627 681 632 681 642C681 673 656 704 624 704C592 704 563 673 563 642C563 632 568 627 580 627Z"} fill={"none"} transform={"translate(584.3 761.8856) scale(0.652542372881356 0.6884987012987013) translate(-563 -627)"} />
        </clipPath>
      </defs>
      <g id={prefix + "-s3-3"}>
        <g>
          <g id={prefix + "-s3-4"} data-group={"seated-body"} data-part={"seated-body"}>
            <g id={prefix + "-s3-5"} data-part={"torso"}>
              <path id={prefix + "-s3-6"} d={"M624.9,811.1c80.9,0,150.5,65.5,161.7,154.6,8.2,69.6-10.2,126.9-53.2,142.3-33.8,13.3-68.6,14.3-108.5,14.3s-74.7-1-108.5-14.3c-43-15.4-61.4-72.7-53.2-142.3,11.3-89.1,80.9-154.6,161.7-154.6Z"} fill={"#1c1d19"} />
            </g>
            <g id={prefix + "-s3-7"} data-part={"belly"}>
              <path id={prefix + "-s3-8"} d={"M624.9,841.9c69.6,0,124.9,66.5,139.2,142.3,13.3,78.8-46.1,120.8-139.2,120.8s-152.5-42-139.2-120.8c14.3-75.8,69.6-142.3,139.2-142.3Z"} fill={"#fffefa"} />
            </g>
            <g id={prefix + "-s3-9"} data-part={"leg-right"}>
              <path id={prefix + "-s3-10"} d={"M738.9,992.1c-36.3,5.9-70.3,37.5-80.9,73.8-11.7,39.9,15.2,73.8,62.1,73.8s91.4-31.6,107.8-71.5c16.4-39.9,5.9-76.2-28.1-85.6-19.9-5.9-43.4,1.2-61,9.4Z"} fill={"#1c1d19"} />
            </g>
            <g id={prefix + "-s3-11"} data-part={"leg-left"}>
              <path id={prefix + "-s3-12"} d={"M450,982.7c-34,9.4-44.5,45.7-28.1,85.6,16.4,39.9,57.4,71.5,107.8,71.5,46.9,0,73.8-34,62.1-73.8-10.5-36.3-44.5-68-80.9-73.8-17.6-8.2-41-15.2-61-9.4Z"} fill={"#1c1d19"} />
            </g>
          </g>
          <g>
            <g id={prefix + "-s3-13"} data-part={"arm-left"}>
              <path id={prefix + "-s3-14"} d={"M528.5,797c22.4,6,29.3,22.4,27.6,42.2-3.4,28.4-20.7,56-32.7,86.2-10.3,25-14.7,50.8-24.1,69.8-7.8,18.1-21.5,28.4-40.5,27.6-25.9,0-44.8-12.9-51.7-31.9-14.7-37.1,11.2-85.3,41.4-123.2,26.7-33.6,58.6-76.7,80.1-70.7Z"} fill={"url(#" + prefix + "-s3-0)"} />
            </g>
            <g id={prefix + "-s3-15"} data-group={"block"} data-part={"block"}>
              <g id={prefix + "-s3-16"} data-part={"block-front"}>
                <path id={prefix + "-s3-17"} d={"M422.1,961.8l57.3,15.4v63.5l-57.3-16.4v-62.4Z"} fill={"#f5c85a"} />
              </g>
              <g id={prefix + "-s3-18"} data-part={"block-side"}>
                <path id={prefix + "-s3-19"} d={"M479.4,977.2l37.9-24.6v63.5l-37.9,24.6v-63.5Z"} fill={"#e9ab43"} />
              </g>
              <g id={prefix + "-s3-20"} data-part={"block-top"}>
                <path id={prefix + "-s3-21"} d={"M422.1,961.8l38.9-24.6,56.3,15.4-37.9,24.6-57.3-15.4Z"} fill={"#ffdf85"} />
              </g>
            </g>
          </g>
          <g className={"panda-mascot__arm-idle panda-mascot__arm-idle--right"} data-motion-part={"arm"}>
            <g className={"panda-mascot__arm-wave panda-mascot__arm-wave--right"} data-motion-part={"arm-wave"}>
              <g id={prefix + "-s3-22"} data-part={"arm-right"}>
                <path id={prefix + "-s3-23"} d={"M801.5,867.6c30.2,37.9,56,86.2,41.4,123.2-6.9,19-25.9,31.9-51.7,31.9-19,.9-32.7-9.5-40.5-27.6-9.5-19-13.8-44.8-24.1-69.8-12.1-30.2-29.3-57.7-32.7-86.2-1.7-19.8,5.2-36.2,27.6-42.2,21.5-6,53.4,37.1,80.1,70.7Z"} fill={"url(#" + prefix + "-s3-1)"} />
              </g>
            </g>
          </g>
          <g id={prefix + "-s3-24"} data-group={"scarf-size"} data-part={"scarf-size"}>
            <g id={prefix + "-s3-25"} data-group={"scarf"} data-part={"scarf"}>
              <g id={prefix + "-s3-26"} data-part={"scarf-cloth"}>
                <path id={prefix + "-s3-27"} d={"M492.3,828.3c32.4-16.2,85.5-22.8,132.7-22.8s102.5,6.6,132.7,22.8c9.6,15.5,8.8,35.4.7,50.1-14,25.1-40.5,45.7-69.3,67.1-22.1,17-45.7,31.7-64.1,43.5-20.6-11.8-44.2-27.3-67.1-42.8-28.7-21.4-51.6-42-64.9-64.1-10.3-17-13.3-38.3-.7-53.8Z"} fill={"#90050e"} />
              </g>
              <g id={prefix + "-s3-28"} data-part={"scarf-fold"}>
                <path id={prefix + "-s3-29"} d={"M487.1,862.2c91.4,27,183,27,274.9,0-3.4,13.3-49.4,30.5-137.8,51.6-75.2-20.1-120.9-37.3-137.1-51.6Z"} fill={"#75020b"} />
              </g>
            </g>
          </g>
          <g className={"panda-mascot__head-breath"}>
            <g className={"panda-mascot__head-action panda-mascot__action"} data-motion-part={"head"}>
              <g id={prefix + "-s3-30"} data-group={"head"} data-part={"head"}>
                <g id={prefix + "-s3-31"} data-group={"ears"} data-part={"ears"}>
                  <g className={"panda-mascot__ear-action panda-mascot__ear-action--left"} data-motion-part={"ear"}>
                    <g id={prefix + "-s3-32"} data-part={"ear-left"}>
                      <path id={prefix + "-s3-33"} d={"M352.1,519.7c0-43.7,35.8-79,79.9-79s79.9,35.4,79.9,79-35.8,79-79.9,79-79.9-35.4-79.9-79Z"} fill={"#1c1d19"} />
                    </g>
                  </g>
                  <g className={"panda-mascot__ear-action panda-mascot__ear-action--right"} data-motion-part={"ear"}>
                    <g id={prefix + "-s3-34"} data-part={"ear-right"}>
                      <path id={prefix + "-s3-35"} d={"M742.4,518c0-44.1,35.8-79.9,79.9-79.9s79.9,35.8,79.9,79.9-35.8,79.9-79.9,79.9-79.9-35.8-79.9-79.9Z"} fill={"#1c1d19"} />
                    </g>
                  </g>
                </g>
                <g id={prefix + "-s3-36"} data-part={"hair-tuft"}>
                  <path id={prefix + "-s3-37"} d={"M569.8,504.1c-9.3-24.7,2.1-50.4,23.7-57.6s26.7,1,32.9,10.3c4.1-27.8,27.8-41.1,49.4-31.9,22.6,10.3,20.6,35,11.3,53.5-12.3,30.8-88.4,46.3-117.2,25.7Z"} fill={"#fffefa"} />
                </g>
                <g id={prefix + "-s3-38"} data-part={"face-base"}>
                  <path id={prefix + "-s3-39"} d={"M624.9,460.4c-79.2,0-125.3,21.8-160.1,47.9-61.8,46.3-100.1,116.6-100.1,182.7s28.7,113.1,76.6,141.8c41.8,25.1,113.1,35.7,183.6,35.7s141.8-10.6,183.6-35.7c47.9-28.7,74.8-62.7,74.8-141.8s-36.5-136.4-98.3-182.7c-34.8-26.1-80.9-47.9-160.1-47.9Z"} fill={"#fffefa"} />
                </g>
                <g id={prefix + "-s3-40"} data-group={"facial-features"} data-part={"facial-features"}>
                  <g id={prefix + "-s3-41"} data-group={"eye-left"} data-part={"eye-left"}>
                    <g id={prefix + "-s3-42"} data-part={"eye-patch-left"}>
                      <path id={prefix + "-s3-43"} d={"M564.2,707.3c-16.3,35-53.6,52.2-83.2,38.4-29.6-13.8-40.4-53.4-24.1-88.4,16.3-35,53.6-52.2,83.2-38.4,29.6,13.8,40.4,53.4,24.1,88.4Z"} fill={"#1c1d19"} />
                    </g>
                    <g className={"panda-mascot__eyes-open panda-mascot__action"} data-motion-part={"eye"}>
                      <g className={"panda-mascot__pupil-look"} data-motion-part={"pupil"}>
                        <g id={prefix + "-s3-44"} data-part={"eye-white-left"}>
                          <ellipse id={prefix + "-s3-45"} cx={"529.2"} cy={"673.6"} rx={"15.4"} ry={"22.4"} fill={"#fff"} />
                        </g>
                      </g>
                    </g>
                  </g>
                  <g id={prefix + "-s3-46"} data-group={"eye-right"} data-part={"eye-right"}>
                    <g id={prefix + "-s3-47"} data-part={"eye-patch-right"}>
                      <path id={prefix + "-s3-48"} d={"M792.1,657.3c16.3,35,5.5,74.6-24.1,88.4-29.6,13.8-66.8-3.4-83.2-38.4-16.3-35-5.5-74.6,24.1-88.4,29.6-13.8,66.8,3.4,83.2,38.4Z"} fill={"#1c1d19"} />
                    </g>
                    <g className={"panda-mascot__eyes-open panda-mascot__action"} data-motion-part={"eye"}>
                      <g className={"panda-mascot__pupil-look"} data-motion-part={"pupil"}>
                        <g id={prefix + "-s3-49"} data-part={"eye-white-right"}>
                          <ellipse id={prefix + "-s3-50"} cx={"720.7"} cy={"673.6"} rx={"15.4"} ry={"22.4"} fill={"#fff"} />
                        </g>
                      </g>
                    </g>
                  </g>
                  <g className={"panda-mascot__cheek panda-mascot__action"}>
                    <g id={prefix + "-s3-51"} data-part={"cheek-left"}>
                      <path id={prefix + "-s3-52"} d={"M503.1,773.6c0,13.5-15.6,24.4-34.8,24.4s-34.8-10.9-34.8-24.4,15.6-24.4,34.8-24.4,34.8,10.9,34.8,24.4Z"} fill={"#fd5d72"} />
                    </g>
                  </g>
                  <g className={"panda-mascot__cheek panda-mascot__action"}>
                    <g id={prefix + "-s3-53"} data-part={"cheek-right"}>
                      <path id={prefix + "-s3-54"} d={"M813.8,773.6c0,13.5-15.6,24.4-34.8,24.4s-34.8-10.9-34.8-24.4,15.6-24.4,34.8-24.4,34.8,10.9,34.8,24.4Z"} fill={"#fd5d72"} />
                    </g>
                  </g>
                  <g id={prefix + "-s3-55"} data-part={"nose"}>
                    <path id={prefix + "-s3-56"} d={"M655.4,719.7c0,10.1-14,18.3-31.3,18.3s-31.3-8.2-31.3-18.3,14-18.3,31.3-18.3,31.3,8.2,31.3,18.3Z"} fill={"#1c1d19"} />
                  </g>
                  <g className={"panda-mascot__mouth panda-mascot__action"} data-motion-part={"mouth"}>
                    <g className={"panda-mascot__mouth-open panda-mascot__action"}>
                      <g id={prefix + "-s3-57"} data-group={"mouth"} data-part={"mouth"}>
                        <g id={prefix + "-s3-58"} data-part={"mouth-cavity"}>
                          <path id={prefix + "-s3-59"} d={"M580 627C594 627 609 629 624 629C639 629 654 627 666 627C676 627 681 632 681 642C681 673 656 704 624 704C592 704 563 673 563 642C563 632 568 627 580 627Z"} fill={"#1c1d19"} transform={"translate(584.3 761.8856) scale(0.652542372881356 0.6884987012987013) translate(-563 -627)"} />
                        </g>
                        <g clipPath={"url(#" + prefix + "-s3-2)"}>
                          <g id={prefix + "-s3-60"} data-group={"tongue-mask"} data-part={"tongue-mask"}>
                            <g id={prefix + "-s3-61"} data-part={"tongue"}>
                              <path id={prefix + "-s3-62"} d={"M668 686C668 704.78 648.3 720 624 720C599.7 720 580 704.78 580 686C580 667.22 599.7 652 624 652C648.3 652 668 667.22 668 686Z"} fill={"#fe7355"} transform={"translate(584.3 761.8856) scale(0.652542372881356 0.6884987012987013) translate(-563 -627)"} />
                            </g>
                          </g>
                        </g>
                      </g>
                    </g>
                    <g className={"panda-mascot__mouth-closed panda-mascot__action"} data-part={"mouth-chew-closed"}>
                      <path d={"M579 639C593 644 608 647 624 647C640 647 655 644 668 639C672 637 675 641 672 645C660 657 641 662 624 662C607 662 587 657 575 645C572 641 575 637 579 639Z"} fill={"#1c1d19"} transform={"translate(584.3 761.8856) scale(0.652542372881356 0.6884987012987013) translate(-563 -627)"} />
                    </g>
                  </g>
                </g>
              </g>
            </g>
          </g>
        </g>
      </g>
    </>
  );
}

function Stage4({ prefix }) {
  return (
    <>
      <defs>
        <linearGradient id={prefix + "-s4-0"} x1={"381.7"} y1={"915.1"} x2={"942.5"} y2={"150.1"} gradientTransform={"translate(1.6471 1252.6233) scale(1 -1)"} gradientUnits={"userSpaceOnUse"}>
          <stop offset={"0"} stopColor={"#1c1d19"} />
          <stop offset={"1"} stopColor={"#191916"} />
        </linearGradient>
        <linearGradient id={prefix + "-s4-1"} x1={"381.9"} y1={"915.1"} x2={"942.7"} y2={"150.1"} gradientTransform={"translate(1248.3529 1252.6233) rotate(-180)"} href={"#" + prefix + "-s4-0"} />
        <clipPath id={prefix + "-s4-2"}>
          <path d={"M580 627C594 627 609 629 624 629C639 629 654 627 666 627C676 627 681 632 681 642C681 673 656 704 624 704C592 704 563 673 563 642C563 632 568 627 580 627Z"} fill={"none"} transform={"translate(575.5 675.7355) scale(0.7966101694915254 0.8397987012987014) translate(-563 -627)"} />
        </clipPath>
      </defs>
      <g id={prefix + "-s4-3"}>
        <g>
          <g id={prefix + "-s4-4"} data-part={"arms"}>
            <g className={"panda-mascot__arm-idle panda-mascot__arm-idle--right"} data-motion-part={"arm"}>
              <g className={"panda-mascot__arm-wave panda-mascot__arm-wave--right"} data-motion-part={"arm-wave"}>
                <g id={prefix + "-s4-5"} data-part={"arm-right"}>
                  <path id={prefix + "-s4-6"} d={"M760.2,767.8c-56.9,21.7-18.5,89.1-4.6,128.9,9.9,24,13.3,68.6,22.4,86.8,13.8,41.4,78.7,29.7,88.6-4.1,24.7-49.7-62.3-209.5-106.4-211.6Z"} fill={"url(#" + prefix + "-s4-0)"} />
                </g>
              </g>
            </g>
          </g>
          <g className={"panda-mascot__leg-action panda-mascot__leg-action--left"} data-motion-part={"leg"}>
            <g id={prefix + "-s4-7"} data-part={"leg-left"}>
              <path id={prefix + "-s4-8"} d={"M545.4,909.4c47.1,0,84.2,34.4,86,79.7-.9,35.3-11.8,86-18.1,111.3-2.7,16.3-22.6,22.6-72.4,22.6-49.8,0-51.6,1.8-63.4-8.1-7.2-5.4-7.2-13.6-4.5-22.6s14.5-13.6,13.6-25.3c-3.6-22.6-13.6-67-17.2-98.7-3.6-34.4,34.4-58.8,76-58.8Z"} fill={"#1c1d19"} />
            </g>
          </g>
          <g className={"panda-mascot__leg-action panda-mascot__leg-action--right"} data-motion-part={"leg"}>
            <g id={prefix + "-s4-9"} data-part={"leg-right"}>
              <path id={prefix + "-s4-10"} d={"M697.8,899.7c-45.4,12.6-72,55.6-61.6,99.7,10.3,33.8,34.3,79.7,47.1,102.5,7,15,27.8,15.8,75.8,2.5s50.2-12,58.9-24.8c5.5-7.2,3.4-15-1.7-23s-17.6-9.2-19.8-20.8c-2.5-22.8-4.8-68.2-9.7-99.7-5.7-34.1-48.8-47.5-89-36.4Z"} fill={"#1c1d19"} />
            </g>
          </g>
          <g id={prefix + "-s4-11"} data-part={"torso"}>
            <path id={prefix + "-s4-12"} d={"M625.2,737.2c88.1,0,155.8,101.2,152.7,195.8-2.4,51.4-45.4,90.5-152.7,90.5s-151.9-38.2-153.5-90.5c-3.1-92.1,64.5-195.8,153.5-195.8Z"} fill={"#1c1d19"} />
          </g>
          <g id={prefix + "-s4-13"} data-part={"belly"}>
            <path id={prefix + "-s4-14"} d={"M786.9,952.8c-1.5-27-1.4-51.5-15.9-80.4-39.2-62.2-244.1-46.6-281,1.6-19.9,26.1-22.5,43.5-17.1,78.8,7.5,49.1,66.8,79.4,155.7,79.4s161.2-21.2,158.3-79.4Z"} fill={"#fffefa"} />
          </g>
          <g id={prefix + "-s4-15"} data-group={"book"} data-part={"book"}>
            <g id={prefix + "-s4-16"} data-part={"book-back"}>
              <rect id={prefix + "-s4-17"} x={"344.5"} y={"855.5"} width={"213.8"} height={"128.1"} rx={"9.6"} ry={"9.6"} transform={"translate(-532.4929 1204.3973) rotate(-80)"} fill={"#396f73"} />
            </g>
            <g id={prefix + "-s4-18"} data-part={"book-pages"}>
              <rect id={prefix + "-s4-19"} x={"352.6"} y={"864"} width={"196.5"} height={"106.9"} rx={"6.7"} ry={"6.7"} transform={"translate(-530.9675 1202.087) rotate(-80)"} fill={"#faf7e9"} />
            </g>
            <g id={prefix + "-s4-20"} data-part={"book-cover"}>
              <path id={prefix + "-s4-21"} d={"M408.8,803.4l78.3,27.5c5.5,2.3,7.7,6.2,6.7,11.9l-31.6,179.3c-1.1,6.3-4.8,8.6-11,6.9l-77.2-28.3c-4.8-2.2-6.8-5.8-5.9-10.8l31.8-180.2c1-5.7,4-7.8,8.9-6.2Z"} fill={"#487f81"} />
            </g>
            <g id={prefix + "-s4-22"} data-part={"book-spine"}>
              <path id={prefix + "-s4-23"} d={"M408.8,803.4l12,4.1-34.8,197.3-12-4.1c-4.8-2.2-6.8-5.8-5.9-10.8l31.8-180.2c1-5.7,4-7.8,8.9-6.2Z"} fill={"#3d7477"} />
            </g>
          </g>
          <g id={prefix + "-s4-24"} data-part={"scarf-knot"}>
            <path id={prefix + "-s4-25"} d={"M756.1,761.9c29-23.5,65.2-24.4,90.5-10-17.2,29-42.5,40.7-76,33.5l-14.5-23.5Z"} fill={"#90050e"} />
          </g>
          <g id={prefix + "-s4-26"} data-part={"arms"}>
            <g id={prefix + "-s4-27"} data-part={"arm-left"}>
              <path id={prefix + "-s4-28"} d={"M383.1,979.4c9.9,33.8,74.9,45.6,88.6,4.1,9.1-18.2,12.5-62.8,22.4-86.8,13.9-39.8,52.3-107.2-4.6-128.9-44.2,2.1-131.1,161.8-106.4,211.6Z"} fill={"url(#" + prefix + "-s4-1)"} />
            </g>
          </g>
          <g id={prefix + "-s4-29"} data-group={"scarf"} data-part={"scarf"}>
            <g id={prefix + "-s4-30"} data-part={"scarf-cloth"}>
              <path id={prefix + "-s4-31"} d={"M462,724.8c39.8-19.9,105-28.1,162.9-28.1s125.8,8.1,162.9,28.1c11.8,19,10.9,43.4.9,61.5-17.2,30.8-49.8,56.1-85.1,82.4-27.2,20.8-56.1,38.9-78.7,53.4-25.3-14.5-54.3-33.5-82.4-52.5-35.3-26.2-63.4-51.6-79.7-78.7-12.7-20.8-16.3-47.1-.9-66.1Z"} fill={"#90050e"} />
            </g>
            <g id={prefix + "-s4-32"} data-part={"scarf-fold"}>
              <path id={prefix + "-s4-33"} d={"M455.6,766.4c112.2,33.2,224.8,33.2,337.6,0-4.2,16.3-60.6,37.4-169.3,63.4-92.3-24.7-148.4-45.9-168.4-63.4Z"} fill={"#75020b"} />
            </g>
          </g>
          <g className={"panda-mascot__head-breath"}>
            <g className={"panda-mascot__head-action panda-mascot__action"} data-motion-part={"head"}>
              <g id={prefix + "-s4-34"} data-group={"head"} data-part={"head"}>
                <g id={prefix + "-s4-35"} data-group={"ears"} data-part={"ears"}>
                  <g className={"panda-mascot__ear-action panda-mascot__ear-action--left"} data-motion-part={"ear"}>
                    <g id={prefix + "-s4-36"} data-part={"ear-left"}>
                      <path id={prefix + "-s4-37"} d={"M326.3,419.8c0-49.1,40.2-88.9,89.8-88.9s89.8,39.8,89.8,88.9-40.2,88.9-89.8,88.9-89.8-39.8-89.8-88.9Z"} fill={"#1c1d19"} />
                    </g>
                  </g>
                  <g className={"panda-mascot__ear-action panda-mascot__ear-action--right"} data-motion-part={"ear"}>
                    <g id={prefix + "-s4-38"} data-part={"ear-right"}>
                      <path id={prefix + "-s4-39"} d={"M748.6,418.8c0-49.1,39.8-88.9,88.9-88.9s88.9,39.8,88.9,88.9-39.8,88.9-88.9,88.9-88.9-39.8-88.9-88.9Z"} fill={"#1c1d19"} />
                    </g>
                  </g>
                </g>
                <g id={prefix + "-s4-40"} data-part={"hair-tuft"}>
                  <path id={prefix + "-s4-41"} d={"M556.2,391.4c1.8-30.2,19.2-64.1,44.9-81.5,20.2-13.7,44-4.6,53.1,12.8,8.2,12.8,5.5,26.6.9,34.8,14.7-18.3,33.9-22.9,47.6-11,13.7,13.7,9.2,33.9-1.8,46.7-32.1,21.1-109.9,21.1-144.7-1.8Z"} fill={"#fffefa"} />
                </g>
                <g id={prefix + "-s4-42"} data-part={"face-base"}>
                  <path id={prefix + "-s4-43"} d={"M624.9,363c-83.4,0-131.9,22.9-168.5,50.4-65,48.8-105.3,122.7-105.3,192.4s30.2,119.1,80.6,149.3c44,26.4,119.1,37.6,193.3,37.6s149.3-11.2,193.3-37.6c50.4-30.2,78.8-66,78.8-149.3s-38.5-143.6-103.5-192.4c-36.6-27.5-85.2-50.4-168.5-50.4Z"} fill={"#fffefa"} />
                </g>
                <g id={prefix + "-s4-44"} data-group={"facial-features"} data-part={"facial-features"}>
                  <g id={prefix + "-s4-45"} data-group={"eye-left"} data-part={"eye-left"}>
                    <g id={prefix + "-s4-46"} data-part={"eye-patch-left"}>
                      <path id={prefix + "-s4-47"} d={"M559.2,622.1c-16.7,35.8-54.7,53.3-85,39.2-30.3-14.1-41.3-54.5-24.6-90.3,16.7-35.8,54.7-53.3,85-39.2,30.3,14.1,41.3,54.5,24.6,90.3Z"} fill={"#1c1d19"} />
                    </g>
                    <g className={"panda-mascot__eyes-open panda-mascot__action"} data-motion-part={"eye"}>
                      <g className={"panda-mascot__pupil-look"} data-motion-part={"pupil"}>
                        <g id={prefix + "-s4-48"} data-part={"eye-white-left"}>
                          <ellipse id={prefix + "-s4-49"} cx={"524.1"} cy={"587.4"} rx={"16.4"} ry={"23.1"} fill={"#fff"} />
                        </g>
                      </g>
                    </g>
                  </g>
                  <g id={prefix + "-s4-50"} data-group={"eye-right"} data-part={"eye-right"}>
                    <g id={prefix + "-s4-51"} data-part={"eye-patch-right"}>
                      <path id={prefix + "-s4-52"} d={"M799.2,571c16.7,35.8,5.7,76.2-24.6,90.3-30.3,14.1-68.3-3.4-85-39.2-16.7-35.8-5.7-76.2,24.6-90.3,30.3-14.1,68.3,3.4,85,39.2Z"} fill={"#1c1d19"} />
                    </g>
                    <g className={"panda-mascot__eyes-open panda-mascot__action"} data-motion-part={"eye"}>
                      <g className={"panda-mascot__pupil-look"} data-motion-part={"pupil"}>
                        <g id={prefix + "-s4-53"} data-part={"eye-white-right"}>
                          <ellipse id={prefix + "-s4-54"} cx={"725.6"} cy={"587.4"} rx={"16.4"} ry={"23.1"} fill={"#fff"} />
                        </g>
                      </g>
                    </g>
                  </g>
                  <g className={"panda-mascot__cheek panda-mascot__action"}>
                    <g id={prefix + "-s4-55"} data-part={"cheek-left"}>
                      <path id={prefix + "-s4-56"} d={"M496.6,692.7c0,14.2-16.4,25.6-36.6,25.6s-36.6-11.5-36.6-25.6,16.4-25.6,36.6-25.6,36.6,11.5,36.6,25.6Z"} fill={"#fd5d72"} />
                    </g>
                  </g>
                  <g className={"panda-mascot__cheek panda-mascot__action"}>
                    <g id={prefix + "-s4-57"} data-part={"cheek-right"}>
                      <path id={prefix + "-s4-58"} d={"M823.7,692.7c0,14.2-16.4,25.6-36.6,25.6s-36.6-11.5-36.6-25.6,16.4-25.6,36.6-25.6,36.6,11.5,36.6,25.6Z"} fill={"#fd5d72"} />
                    </g>
                  </g>
                  <g id={prefix + "-s4-59"} data-part={"nose"}>
                    <path id={prefix + "-s4-60"} d={"M656.9,635.9c0,10.6-14.8,19.2-33,19.2s-33-8.6-33-19.2,14.8-19.2,33-19.2,33,8.6,33,19.2Z"} fill={"#1c1d19"} />
                  </g>
                  <g className={"panda-mascot__mouth panda-mascot__action"} data-motion-part={"mouth"}>
                    <g className={"panda-mascot__mouth-open panda-mascot__action"}>
                      <g id={prefix + "-s4-61"} data-group={"mouth"} data-part={"mouth"}>
                        <g id={prefix + "-s4-62"} data-part={"mouth-cavity"}>
                          <path id={prefix + "-s4-63"} d={"M580 627C594 627 609 629 624 629C639 629 654 627 666 627C676 627 681 632 681 642C681 673 656 704 624 704C592 704 563 673 563 642C563 632 568 627 580 627Z"} fill={"#1c1d19"} transform={"translate(575.5 675.7355) scale(0.7966101694915254 0.8397987012987014) translate(-563 -627)"} />
                        </g>
                        <g clipPath={"url(#" + prefix + "-s4-2)"}>
                          <g id={prefix + "-s4-64"} data-group={"tongue-mask"} data-part={"tongue-mask"}>
                            <g id={prefix + "-s4-65"} data-part={"tongue"}>
                              <path id={prefix + "-s4-66"} d={"M668 686C668 704.78 648.3 720 624 720C599.7 720 580 704.78 580 686C580 667.22 599.7 652 624 652C648.3 652 668 667.22 668 686Z"} fill={"#fe7355"} transform={"translate(575.5 675.7355) scale(0.7966101694915254 0.8397987012987014) translate(-563 -627)"} />
                            </g>
                          </g>
                        </g>
                      </g>
                    </g>
                    <g className={"panda-mascot__mouth-closed panda-mascot__action"} data-part={"mouth-chew-closed"}>
                      <path d={"M579 639C593 644 608 647 624 647C640 647 655 644 668 639C672 637 675 641 672 645C660 657 641 662 624 662C607 662 587 657 575 645C572 641 575 637 579 639Z"} fill={"#1c1d19"} transform={"translate(575.5 675.7355) scale(0.7966101694915254 0.8397987012987014) translate(-563 -627)"} />
                    </g>
                  </g>
                </g>
              </g>
            </g>
          </g>
        </g>
      </g>
    </>
  );
}

function Stage5({ prefix, wardrobe }) {
  return (
    <>
      <defs>
        <linearGradient id={prefix + "-s5-0"} x1={"219.4"} y1={"932.6"} x2={"849.7"} y2={"72.9"} gradientTransform={"translate(0 1254) scale(1 -1)"} gradientUnits={"userSpaceOnUse"}>
          <stop offset={"0"} stopColor={"#1c1d19"} />
          <stop offset={"1"} stopColor={"#191916"} />
        </linearGradient>
        <linearGradient id={prefix + "-s5-1"} x1={"219.4"} y1={"932.6"} x2={"849.7"} y2={"72.9"} gradientTransform={"translate(1249.8884 1254) rotate(-180)"} href={"#" + prefix + "-s5-0"} />
        <linearGradient id={prefix + "-s5-2"} x1={"290.1"} y1={"1087.6"} x2={"967.2"} y2={"164"} gradientTransform={"translate(35.9519 1316.5559) rotate(-4.6413) scale(1 -1)"} gradientUnits={"userSpaceOnUse"}>
          <stop offset={"0"} stopColor={"#1c1d19"} />
          <stop offset={"1"} stopColor={"#191916"} />
        </linearGradient>
        <linearGradient id={prefix + "-s5-3"} x1={"290.1"} y1={"1087.6"} x2={"967.2"} y2={"164"} gradientTransform={"translate(1213.9365 1316.5559) rotate(-175.3587)"} href={"#" + prefix + "-s5-2"} />
        <linearGradient id={prefix + "-s5-4"} x1={"214.5"} y1={"927.3"} x2={"846.5"} y2={"65.3"} gradientTransform={"translate(0 1254) scale(1 -1)"} gradientUnits={"userSpaceOnUse"}>
          <stop offset={"0"} stopColor={"#1c1d19"} />
          <stop offset={"1"} stopColor={"#191916"} />
        </linearGradient>
        <clipPath id={prefix + "-s5-5"}>
          <path d={"M625,682c102.1,0,180.6,122,176.9,236-2.7,62-52.6,109-176.9,109s-176-46-177.8-109c-3.6-111,74.8-236,177.8-236Z"} fill={"none"} />
        </clipPath>
        <radialGradient id={prefix + "-s5-6"} cx={"516.4"} cy={"-2"} fx={"516.4"} fy={"-2"} r={"739.7"} gradientTransform={"translate(54.9761 1257.4) scale(.912 -.9)"} gradientUnits={"userSpaceOnUse"}>
          <stop offset={"0"} stopColor={"#fffefa"} />
          <stop offset={"1"} stopColor={"#fdfcf8"} />
        </radialGradient>
        <linearGradient id={prefix + "-s5-7"} x1={"507.7"} y1={"575.2"} x2={"808.6"} y2={"406"} gradientTransform={"translate(0 1254) scale(1 -1)"} gradientUnits={"userSpaceOnUse"}>
          <stop offset={"0"} stopColor={"#940009"} />
          <stop offset={"1"} stopColor={"#840309"} />
        </linearGradient>
        <linearGradient id={prefix + "-s5-8"} x1={"315.9"} y1={"1015.6"} x2={"955.9"} y2={"142.6"} gradientTransform={"translate(0 1254) scale(1 -1)"} gradientUnits={"userSpaceOnUse"}>
          <stop offset={"0"} stopColor={"#1c1d19"} />
          <stop offset={"1"} stopColor={"#191916"} />
        </linearGradient>
        <linearGradient id={prefix + "-s5-9"} x1={"615.6"} y1={"1235.3"} x2={"1255.6"} y2={"362.3"} gradientTransform={"translate(0 1254) scale(1 -1)"} gradientUnits={"userSpaceOnUse"}>
          <stop offset={"0"} stopColor={"#1c1d19"} />
          <stop offset={"1"} stopColor={"#191916"} />
        </linearGradient>
        <radialGradient id={prefix + "-s5-10"} cx={"520"} cy={"814"} fx={"520"} fy={"814"} r={"750"} gradientTransform={"translate(0 1254) scale(1 -1)"} gradientUnits={"userSpaceOnUse"}>
          <stop offset={"0"} stopColor={"#fffefa"} />
          <stop offset={"1"} stopColor={"#fdfcf8"} />
        </radialGradient>
        <radialGradient id={prefix + "-s5-11"} cx={"520"} cy={"814"} fx={"520"} fy={"814"} r={"750"} gradientTransform={"translate(0 1254) scale(1 -1)"} gradientUnits={"userSpaceOnUse"}>
          <stop offset={"0"} stopColor={"#fffefa"} />
          <stop offset={"1"} stopColor={"#fdfcf8"} />
        </radialGradient>
        <linearGradient id={prefix + "-s5-12"} x1={"286.6"} y1={"994.2"} x2={"926.6"} y2={"121.2"} gradientTransform={"translate(0 1254) scale(1 -1)"} gradientUnits={"userSpaceOnUse"}>
          <stop offset={"0"} stopColor={"#1c1d19"} />
          <stop offset={"1"} stopColor={"#191916"} />
        </linearGradient>
        <linearGradient id={prefix + "-s5-13"} x1={"457"} y1={"1119.1"} x2={"1097"} y2={"246.1"} gradientTransform={"translate(0 1254) scale(1 -1)"} gradientUnits={"userSpaceOnUse"}>
          <stop offset={"0"} stopColor={"#1c1d19"} />
          <stop offset={"1"} stopColor={"#191916"} />
        </linearGradient>
        <linearGradient id={prefix + "-s5-14"} x1={"351"} y1={"1041.4"} x2={"991"} y2={"168.4"} gradientTransform={"translate(0 1254) scale(1 -1)"} gradientUnits={"userSpaceOnUse"}>
          <stop offset={"0"} stopColor={"#1c1d19"} />
          <stop offset={"1"} stopColor={"#191916"} />
        </linearGradient>
        <linearGradient id={prefix + "-s5-15"} x1={"319.6"} y1={"1018.4"} x2={"959.6"} y2={"145.4"} gradientTransform={"translate(0 1254) scale(1 -1)"} gradientUnits={"userSpaceOnUse"}>
          <stop offset={"0"} stopColor={"#1c1d19"} />
          <stop offset={"1"} stopColor={"#191916"} />
        </linearGradient>
        <clipPath id={prefix + "-s5-16"}>
          <path d={"M580 627C594 627 609 629 624 629C639 629 654 627 666 627C676 627 681 632 681 642C681 673 656 704 624 704C592 704 563 673 563 642C563 632 568 627 580 627Z"} fill={"none"} transform={"translate(563 622.872) scale(1 1.0536103896103897) translate(-563 -627)"} />
        </clipPath>
      </defs>
      <g id={prefix + "-s5-17"}>
        <PandaWardrobeArtwork wardrobe={wardrobe} slot="back" />
        <g id={prefix + "-s5-18"} data-part={"base"}>
          <g id={prefix + "-s5-19"} data-part={"body-size"}>
            <g className={"panda-mascot__leg-action panda-mascot__leg-action--right"} data-motion-part={"leg"}>
              <path id={prefix + "-s5-20"} d={"M724.7,887c-49.4,0-88.4,38-90.3,88,1,39,12.4,95,19,123,2.9,18,23.8,25,76,25s54.2,2,66.5-9c7.6-6,7.6-15,4.8-25-2.9-10-15.2-15-14.3-28,3.8-25,14.3-74,18.1-109,3.8-38-36.1-65-79.8-65Z"} data-part={"leg-right"} fill={"url(#" + prefix + "-s5-0)"} />
            </g>
            <g className={"panda-mascot__leg-action panda-mascot__leg-action--left"} data-motion-part={"leg"}>
              <path id={prefix + "-s5-21"} d={"M445.3,952c3.8,35,14.3,84,18.1,109,1,13-11.4,18-14.3,28-2.9,10-2.9,19,4.8,25,12.4,11,14.3,9,66.5,9,52.3,0,73.2-7,76-25,6.7-28,18.1-84,19-123-1.9-50-40.9-88-90.3-88-43.7,0-83.6,27-79.8,65Z"} data-part={"leg-left"} fill={"url(#" + prefix + "-s5-1)"} />
            </g>
            <g id={prefix + "-s5-22"} data-part={"arms"}>
              <g className={"panda-mascot__arm-idle panda-mascot__arm-idle--right"} data-motion-part={"arm"}>
                <g className={"panda-mascot__arm-wave panda-mascot__arm-wave--right"} data-motion-part={"arm-wave"}>
                  <g id={prefix + "-s5-23"} data-part={"arm-right"}>
                    <path id={prefix + "-s5-24"} d={"M732.6,690c-66.4,31.6-13.6,109.1,7.1,155.6,14.3,27.9,22.7,81.2,35.5,102.3,20.6,48.5,97.6,28,106.2-13.6,24.8-62.2-95.4-246-148.8-244.2Z"} fill={"url(#" + prefix + "-s5-2)"} />
                  </g>
                  <PandaWardrobeArtwork wardrobe={wardrobe} slot="sleeve-right" />
                </g>
              </g>
            </g>
            <g id={prefix + "-s5-25"} data-part={"arms"}>
              <g className={"panda-mascot__arm-idle panda-mascot__arm-idle--left"} data-motion-part={"arm"}>
                <g className={"panda-mascot__arm-wave panda-mascot__arm-wave--left"} data-motion-part={"arm-wave"}>
                  <g id={prefix + "-s5-26"} data-part={"arm-left"}>
                    <path id={prefix + "-s5-27"} d={"M368.5,934.2c8.6,41.7,85.6,62.2,106.2,13.6,12.7-21,21.2-74.4,35.5-102.3,20.6-46.5,73.5-123.9,7.1-155.6-53.4-1.8-173.6,182-148.8,244.2Z"} fill={"url(#" + prefix + "-s5-3)"} />
                  </g>
                  <PandaWardrobeArtwork wardrobe={wardrobe} slot="sleeve-left" />
                </g>
              </g>
            </g>
            <g id={prefix + "-s5-28"} data-part={"body"}>
              <path id={prefix + "-s5-29"} d={"M625,682c102.1,0,180.6,122,176.9,236-2.7,62-52.6,109-176.9,109s-176-46-177.8-109c-3.6-111,74.8-236,177.8-236Z"} data-part={"torso"} fill={"url(#" + prefix + "-s5-4)"} />
              <g clipPath={"url(#" + prefix + "-s5-5)"}>
                <g id={prefix + "-s5-30"} data-part={"belly-clip"}>
                  <path id={prefix + "-s5-31"} d={"M812.4,941.8c-1.7-32.5,8.2-59.8-23.3-95-34.7-38.8-73.4-58-164.2-58s-129.4,19.2-164.2,58c-31.5,35.2-21.5,62.5-23.3,95-6.4,73.7,77.1,95.7,187.4,95.7s193.8-22,187.4-95.7Z"} data-part={"belly"} fill={"url(#" + prefix + "-s5-6)"} />
                </g>
              </g>
            </g>
            <g id={prefix + "-s5-32"} data-part={"scarf"} display={wardrobe?.neck || wardrobe?.costume ? "none" : undefined}>
              <path id={prefix + "-s5-33"} d={"M456.8,683c41.1-22,108.4-31,168.2-31s129.9,9,168.2,31c12.1,21,11.2,48,.9,68-17.8,34-51.4,62-87.8,91-28,23-57.9,43-81.3,59-26.2-16-56.1-37-85-58-36.4-29-65.4-57-82.2-87-13.1-23-16.8-52-.9-73Z"} data-part={"scarf-cloth"} fill={"url(#" + prefix + "-s5-7)"} />
              <path id={prefix + "-s5-34"} d={"M450.2,729c115.9,36.7,232,36.7,348.5,0-4.4,18-62.6,41.3-174.7,70-95.3-27.3-153.2-50.7-173.8-70Z"} data-part={"scarf-fold"} fill={"#720107"} />
            </g>
          </g>
          <PandaWardrobeArtwork wardrobe={wardrobe} slot="hat-back" motion="head" />
          <PandaWardrobeArtwork wardrobe={wardrobe} slot="costume" />
          <PandaWardrobeArtwork wardrobe={wardrobe} slot="neck" />
          <g id={prefix + "-s5-35"} data-part={"head-size"}>
            <g id={prefix + "-s5-36"} data-part={"head-breath"}>
              <g id={prefix + "-s5-37"} data-part={"head-action"}>
                <g className={"panda-mascot__head-breath"}>
                  <g className={"panda-mascot__head-action panda-mascot__action"} data-motion-part={"head"}>
                    <g id={prefix + "-s5-38"} data-part={"head"}>
                      <g id={prefix + "-s5-39"} data-part={"ears"}>
                        <g className={"panda-mascot__ear-action panda-mascot__ear-action--left"} data-motion-part={"ear"}>
                          <g id={prefix + "-s5-40"} data-part={"ear-left"}>
                            <path id={prefix + "-s5-41"} d={"M299,349c0-53.6,43.9-97,98-97s98,43.4,98,97-43.9,97-98,97-98-43.4-98-97Z"} fill={"url(#" + prefix + "-s5-8)"} />
                          </g>
                        </g>
                        <g className={"panda-mascot__ear-action panda-mascot__ear-action--right"} data-motion-part={"ear"}>
                          <g id={prefix + "-s5-42"} data-part={"ear-right"}>
                            <path id={prefix + "-s5-43"} d={"M760,348c0-53.6,43.4-97,97-97s97,43.4,97,97-43.4,97-97,97-97-43.4-97-97Z"} fill={"url(#" + prefix + "-s5-9)"} />
                          </g>
                        </g>
                      </g>
                      <g id={prefix + "-s5-44"} data-part={"face"}>
                        <g id={prefix + "-s5-45"} data-part={"hair-tuft"}>
                          <path id={prefix + "-s5-46"} d={"M499,297c0-23.8,19.2-43,43-43s18,2.8,24,8c4,3.5,7,8,7,5,0-31,24-56,54-56s54,25,54,56,3-1.5,7-5c6-5.2,15-8,24-8,23.8,0,43,19.2,43,43,0,41-57,74-128,74s-128-33-128-74Z"} fill={"url(#" + prefix + "-s5-10)"} />
                        </g>
                        <g id={prefix + "-s5-47"} data-part={"face-base"}>
                          <path id={prefix + "-s5-48"} d={"M625,287c-91,0-144,25-184,55-71,53.2-115,134-115,210s33,130,88,163c48,28.8,130,41,211,41s163-12.2,211-41c55-33,86-72,86-163s-42-156.8-113-210-93-55-184-55Z"} fill={"url(#" + prefix + "-s5-11)"} />
                        </g>
                      </g>
                      <g id={prefix + "-s5-49"} data-part={"facial-features"}>
                        <g id={prefix + "-s5-50"} data-part={"eyes"}>
                          <g id={prefix + "-s5-51"} data-part={"eye-left"}>
                            <g id={prefix + "-s5-52"} data-part={"eye-patch-left"}>
                              <path id={prefix + "-s5-53"} d={"M553.3,569.9c-18.2,39-59.8,58.2-92.8,42.8-33-15.4-45.1-59.5-26.9-98.6,18.2-39,59.8-58.2,92.8-42.8,33,15.4,45.1,59.5,26.9,98.6Z"} fill={"url(#" + prefix + "-s5-12)"} />
                            </g>
                            <g id={prefix + "-s5-54"} data-part={"eye-open-left"}>
                              <g className={"panda-mascot__eyes-open panda-mascot__action"} data-motion-part={"eye"}>
                                <g className={"panda-mascot__pupil-look"} data-motion-part={"pupil"}>
                                  <g id={prefix + "-s5-55"} data-part={"eye-white-left"}>
                                    <ellipse id={prefix + "-s5-56"} cx={"515"} cy={"532"} rx={"16"} ry={"23"} fill={"#fff"} />
                                  </g>
                                </g>
                              </g>
                              <g className={"panda-mascot__eyes-squeezed"} data-part={"eye-squeezed-left"}>
                                <path d={"M499 514L531 532L499 550"} fill={"none"} stroke={"#fff"} strokeWidth={"11"} strokeLinecap={"round"} strokeLinejoin={"round"} />
                              </g>
                            </g>
                          </g>
                          <g id={prefix + "-s5-57"} data-part={"eye-right"}>
                            <g id={prefix + "-s5-58"} data-part={"eye-patch-right"}>
                              <path id={prefix + "-s5-59"} d={"M815.3,514.1c18.2,39,6.2,83.2-26.9,98.6-33,15.4-74.6-3.8-92.8-42.8-18.2-39-6.2-83.2,26.9-98.6,33-15.4,74.6,3.8,92.8,42.8Z"} fill={"url(#" + prefix + "-s5-13)"} />
                            </g>
                            <g id={prefix + "-s5-60"} data-part={"eye-open-right"}>
                              <g className={"panda-mascot__eyes-open panda-mascot__action"} data-motion-part={"eye"}>
                                <g className={"panda-mascot__pupil-look"} data-motion-part={"pupil"}>
                                  <g id={prefix + "-s5-61"} data-part={"eye-white-right"}>
                                    <ellipse id={prefix + "-s5-62"} cx={"735"} cy={"532"} rx={"16"} ry={"23"} fill={"#fff"} />
                                  </g>
                                </g>
                              </g>
                              <g className={"panda-mascot__eyes-squeezed"} data-part={"eye-squeezed-right"}>
                                <path d={"M751 514L719 532L751 550"} fill={"none"} stroke={"#fff"} strokeWidth={"11"} strokeLinecap={"round"} strokeLinejoin={"round"} />
                              </g>
                            </g>
                          </g>
                        </g>
                        <g id={prefix + "-s5-63"} data-part={"cheeks"}>
                          <g className={"panda-mascot__cheek panda-mascot__action"}>
                            <g id={prefix + "-s5-64"} data-part={"cheek-left"}>
                              <path id={prefix + "-s5-65"} d={"M485,647c0,15.5-17.9,28-40,28s-40-12.5-40-28,17.9-28,40-28,40,12.5,40,28Z"} fill={"#fd5d72"} />
                            </g>
                          </g>
                          <g className={"panda-mascot__cheek panda-mascot__action"}>
                            <g id={prefix + "-s5-66"} data-part={"cheek-right"}>
                              <path id={prefix + "-s5-67"} d={"M842,647c0,15.5-17.9,28-40,28s-40-12.5-40-28,17.9-28,40-28,40,12.5,40,28Z"} fill={"#fd5d72"} />
                            </g>
                          </g>
                        </g>
                        <g id={prefix + "-s5-68"} data-part={"nose"}>
                          <path id={prefix + "-s5-69"} d={"M660,585c0,11.6-16.1,21-36,21s-36-9.4-36-21,16.1-21,36-21,36,9.4,36,21Z"} fill={"url(#" + prefix + "-s5-14)"} />
                        </g>
                        <g className={"panda-mascot__mouth panda-mascot__action"} data-motion-part={"mouth"}>
                          <g className={"panda-mascot__mouth-open panda-mascot__action"}>
                            <g id={prefix + "-s5-70"} data-part={"mouth"}>
                              <g id={prefix + "-s5-71"} data-part={"mouth-cavity"}>
                                <path id={prefix + "-s5-72"} d={"M580 627C594 627 609 629 624 629C639 629 654 627 666 627C676 627 681 632 681 642C681 673 656 704 624 704C592 704 563 673 563 642C563 632 568 627 580 627Z"} fill={"url(#" + prefix + "-s5-15)"} transform={"translate(563 622.872) scale(1 1.0536103896103897) translate(-563 -627)"} />
                              </g>
                              <g clipPath={"url(#" + prefix + "-s5-16)"}>
                                <g id={prefix + "-s5-73"} data-part={"tongue-clip"}>
                                  <g id={prefix + "-s5-74"} data-part={"tongue"}>
                                    <path id={prefix + "-s5-75"} d={"M668 686C668 704.78 648.3 720 624 720C599.7 720 580 704.78 580 686C580 667.22 599.7 652 624 652C648.3 652 668 667.22 668 686Z"} fill={"#fe7355"} transform={"translate(563 622.872) scale(1 1.0536103896103897) translate(-563 -627)"} />
                                  </g>
                                </g>
                              </g>
                            </g>
                          </g>
                          <g className={"panda-mascot__mouth-closed panda-mascot__action"} data-part={"mouth-chew-closed"}>
                            <path d={"M579 639C593 644 608 647 624 647C640 647 655 644 668 639C672 637 675 641 672 645C660 657 641 662 624 662C607 662 587 657 575 645C572 641 575 637 579 639Z"} fill={"#1c1d19"} transform={"translate(563 622.872) scale(1 1.0536103896103897) translate(-563 -627)"} />
                          </g>
                        </g>
                      </g>
                    </g>
                    <PandaWardrobeArtwork wardrobe={wardrobe} slot="hat-front" />
                  </g>
                </g>
              </g>
            </g>
          </g>
          <PandaWardrobeArtwork wardrobe={wardrobe} slot="hand" motion="arm-right" />
        </g>
      </g>
    </>
  );
}

const STAGES = [Stage0, Stage1, Stage2, Stage3, Stage4, Stage5];

export default function PandaGrowthArtwork({ stage, prefix, wardrobe = null }) {
  const Artwork = STAGES[stage];
  return <Artwork prefix={prefix} wardrobe={wardrobe} />;
}
